apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-platform-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
        revision: main
        directories:
          - path: apps/data-platform/*
  template:
    metadata:
      name: 'data-platform-{{path.basename}}'
    spec:
      project: data-platform
      source:
        repoURL: 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: data-platform
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
