apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: identity-platform
  namespace: argocd
spec:
  description: "Argo CD project for Identity Platform workloads"
  destinations:
    - namespace: identity-platform
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: batch
      kind: Job
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
  clusterResourceWhitelist: []
  orphanedResources:
    warn: true

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-engineering
  namespace: argocd
spec:
  description: "Argo CD project for Platform Engineering workloads"
  destinations:
    - namespace: platform-engineering
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: batch
      kind: Job
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
  clusterResourceWhitelist: []
  orphanedResources:
    warn: true

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-platform
  namespace: argocd
spec:
  description: "Argo CD project for Data Platform workloads"
  destinations:
    - namespace: data-platform
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: batch
      kind: Job
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
  clusterResourceWhitelist: []
  orphanedResources:
    warn: true

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-infra
  namespace: argocd
spec:
  description: "ArgoCD Project for Platform Infrastructure & Crossplane Claims"
  destinations:
    - namespace: identity-platform
      server: https://kubernetes.default.svc
    - namespace: platform-engineering
      server: https://kubernetes.default.svc
    - namespace: data-platform
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
  namespaceResourceWhitelist:
    - group: idp.io
      kind: ObjectBucket
    - group: idp.io
      kind: PostgresSQLInstance
    - group: idp.io
      kind: RedisInstance
    - group: idp.io
      kind: ServerInstance
    - group: external-secrets.io
      kind: ExternalSecret
    - group: external-secrets.io
      kind: SecretStore
  clusterResourceWhitelist: []
  orphanedResources:
    warn: true
