apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  labels:
    app.kubernetes.io/managed-by: platform-team
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-workload
  labels:
    app.kubernetes.io/managed-by: platform-team
    platform.idp.io/purpose: tenant-workload
automountServiceAccountToken: false
