apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-inter-namespace
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-clients
spec:
  podSelector:
    matchLabels:
      platform.idp.io/postgres-client: "true"
  policyTypes: [Egress]
  egress:
    - to: ${DATA_SUBNET_PEERS}
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-clients
spec:
  podSelector:
    matchLabels:
      platform.idp.io/redis-client: "true"
  policyTypes: [Egress]
  egress:
    - to: ${DATA_SUBNET_PEERS}
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alb-targets
spec:
  podSelector:
    matchLabels:
      platform.idp.io/alb-target: "true"
  policyTypes: [Ingress]
  ingress:
    - from: ${PUBLIC_SUBNET_PEERS}
      ports:
        - protocol: TCP
          port: http
