apiVersion: idp.io/v1alpha1
kind: PostgresSQLInstance
metadata:
  name: team-alpha-db
  namespace: team-alpha
spec:
  storageGB: 20
  size: small
  writeConnectionSecretToRef:
    name: team-alpha-db-conn
