apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  namespace: team-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: 851236938302.dkr.ecr.us-east-1.amazonaws.com/idp-team-alpha-login-app:246b429077dd2bc39e9a8e05c635f05e62b10902
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: team-alpha-db-conn
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: team-alpha-db-conn
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: team-alpha-db-conn
                  key: password
            - name: DB_NAME
              value: postgres
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: team-alpha-db-conn
                  key: port
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
  namespace: team-alpha
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: login-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-app-ingress
  namespace: team-alpha
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: login.idp-prod.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: login-app
                port:
                  number: 3000
