version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
    groups:
      actions: {patterns: ['*']}
  - package-ecosystem: npm
    directory: /platform/validation
    schedule: {interval: weekly}
    groups:
      validation: {patterns: ['*']}
  - package-ecosystem: npm
    directory: /platform/developer-portal/local-catalog
    schedule: {interval: weekly}
  - package-ecosystem: pip
    directory: /templates/backstage/python-fastapi/skeleton
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /templates/backstage/nodejs-service/skeleton
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /templates/backstage/python-fastapi/skeleton
    schedule: {interval: weekly}
  - package-ecosystem: terraform
    directory: /infrastructure/terraform/stacks/prod/eks
    schedule: {interval: monthly}
  - package-ecosystem: terraform
    directory: /infrastructure/terraform/stacks/prod/network
    schedule: {interval: monthly}
  - package-ecosystem: npm
    directories: ['/apps/*/*']
    schedule: {interval: weekly}
    groups:
      service-dependencies: {patterns: ['*']}
  - package-ecosystem: pip
    directories: ['/apps/*/*']
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directories: ['/apps/*/*']
    schedule: {interval: weekly}
