apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: redisinstances.idp.io
spec:
  scope: Namespaced
  group: idp.io
  names:
    kind: RedisInstance
    plural: redisinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  default: small
                  enum:
                    - small
                    - medium
              required:
                - size
