apiVersion: v1
kind: Namespace
metadata:
  name: platform-engineering
  labels:
    platform.idp.io/image-registry: 851236938302.dkr.ecr.us-east-1.amazonaws.com
    platform.idp.io/tenant: "true"
    platform.idp.io/workload-policy: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.36
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.36
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.36
