apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgressqlinstances.idp.io
spec:
  group: idp.io
  names:
    kind: XPostgresSQLInstance
    plural: xpostgressqlinstances
  claimNames:
    kind: PostgresSQLInstance
    plural: postgressqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storageGB:
                  type: integer
                  default: 20
                size:
                  type: string
                  default: small
              required:
                - storageGB
                - size
