replicaCount: 1
admissionController:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

backgroundController:
  replicas: 1

cleanupController:
  replicas: 1

reportsController:
  replicas: 1
