apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.resource_name }}-password
  namespace: ${{ values.owner }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: ${{ values.resource_name }}-password
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: idp/${{ values.owner }}/${{ values.password_secret_name }}
        property: password
