apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-viewers
  namespace: platform-engineering
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: idp:tenant:platform-engineering:viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idp-tenant-viewer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-operators-view
  namespace: platform-engineering
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: idp:tenant:platform-engineering:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idp-tenant-viewer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-operators-actions
  namespace: platform-engineering
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: idp:tenant:platform-engineering:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idp-tenant-operator-actions
