apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.resource_name }}
  annotations:
    backstage.io/managed-by-origin-location: url:https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
spec:
  type: resource
  lifecycle: production
  owner: ${{ values.owner }}
  dependsOn:
    - resource:${{ values.resource_name }}
