apiVersion: idp.io/v1alpha1
kind: PostgresSQLInstance
metadata:
  name: ${{ values.resource_name }}
  namespace: ${{ values.owner }}
spec:
  storageGB: ${{ values.storage_gb }}
  size: ${{ values.size }}
