apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: internal-developer-platform
  description: Internal Developer Platform Domain
spec:
  owner: platform-engineering
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform-services
  description: Services managed through the internal developer platform
spec:
  owner: platform-engineering
  domain: internal-developer-platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: identity-platform
  description: Identity and access platform engineering team
spec:
  type: team
  profile:
    displayName: Identity Platform
    email: identity-platform@idp.internal
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  description: Internal developer platform engineering team
spec:
  type: team
  profile:
    displayName: Platform Engineering
    email: platform-engineering@idp.internal
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: data-platform
  description: Data infrastructure and analytics platform team
spec:
  type: team
  profile:
    displayName: Data Platform
    email: data-platform@idp.internal
  children: []
