apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-claims
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - team: team-alpha
            path: infrastructure/crossplane/claims/team-alpha
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{team}}-infra-claims'
    spec:
      project: platform-infra
      source:
        repoURL: 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{team}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
