apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-alpha-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
        revision: HEAD
        directories:
          - path: apps/team-alpha/*
  template:
    metadata:
      name: 'team-alpha-{{path.basename}}'
    spec:
      project: team-alpha
      source:
        repoURL: 'https://github.com/amr-elzoghby/Internal-Developer-Platform.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: team-alpha
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
