apiVersion: idp.io/v1alpha1
kind: RedisInstance
metadata:
  name: team-alpha-cache
  namespace: team-alpha
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  size: small
