apiVersion: idp.io/v1alpha1
kind: ServerInstance
metadata:
  name: team-alpha-web-server
  namespace: team-alpha
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  size: small
