apiVersion: idp.io/v1alpha1
kind: ServerInstance
metadata:
  name: team-alpha-web-server
  namespace: team-alpha
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    platform.idp.io/ami-source: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    platform.idp.io/ami-reviewed-at: "2026-09-01"
spec:
  size: small
  ami: ami-081b0a6eac00b4f53
