apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-alpha-db-password-es
  namespace: team-alpha
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: team-alpha-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: idp/team-alpha/db-password
        property: password
