apiVersion: idp.io/v1alpha1
kind: RedisInstance
metadata:
  name: identity-platform-cache
  namespace: identity-platform
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  size: small
