apiVersion: idp.io/v1alpha1
kind: ObjectBucket
metadata:
  name: identity-platform-s3-bucket
  namespace: identity-platform
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  region: us-east-1
