apiVersion: idp.io/v1alpha1
kind: RedisInstance
metadata:
  name: identity-platform-cache
  namespace: identity-platform
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  crossplane:
    compositionUpdatePolicy: Manual
  owner: identity-platform
  expiresOn: "2026-12-31"
  size: small
