apiVersion: idp.io/v1alpha1
kind: PostgresSQLInstance
metadata:
  name: identity-platform-db
  namespace: identity-platform
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  storageGB: 20
  size: small
