apiVersion: idp.io/v1alpha1
kind: ServerInstance
metadata:
  name: identity-platform-utility-server
  namespace: identity-platform
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  crossplane:
    compositionUpdatePolicy: Manual
  owner: identity-platform
  expiresOn: "2026-12-31"
  size: small
  image: al2023-ssm
